package uz.pdp.taskmanagement.entity.enumerators;

public enum Permission {
    USER_DELETE,
    USER_CREATE,
    USER_UPDATE,
    USER_READ,
    USER_ALL,

    STUDENT_DELETE,
    STUDENT_CREATE,
    STUDENT_UPDATE,
    STUDENT_READ,
    STUDENT_ALL,

    GROUP_DELETE,
    GROUP_CREATE,
    GROUP_UPDATE,
    GROUP_READ,
    GROUP_ALL,

    MODULE_DELETE,
    MODULE_CREATE,
    MODULE_UPDATE,
    MODULE_READ,
    MODULE_ALL,

    LESSON_DELETE,
    LESSON_CREATE,
    LESSON_UPDATE,
    LESSON_READ,
    LESSON_ALL,

    ATTENDANCE_DELETE,
    ATTENDANCE_CREATE,
    ATTENDANCE_UPDATE,
    ATTENDANCE_READ,
    ATTENDANCE_ALL,

    DEPARTMENT_DELETE,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_READ,
    DEPARTMENT_ALL,

}
